services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=spring-boot-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=spring-boot-user'
    ports:
      - '5432:5432'