receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  postgresql:
    endpoint: host.docker.internal:5432
    transport: tcp
    username: spring-boot-user
    password: secret
    tls:
      insecure: true
    databases:
      - spring-boot-db
    collection_interval: 10s
    query_sample_collection:
      enabled: false
    top_query_collection:
      enabled: true
      top_n_query: 100

exporters:
  debug:
    verbosity: normal  # Can be 'normal' or 'detailed'

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]